# -*- coding: utf-8 -*-
"""
Highrise Bot — Komplette Emote-Liste
Gesamt: 307 Emotes (bereinigt, ohne Duplikate)
Quellen: Notion-Seiten von itzvini + bestehende Bot-Listen
"""

ALL_EMOTES: list[dict] = [
    {"number": 1, "name": "Advanced Shy", "id": "emote-shy2", "is_free": True, "duration": 4.99},
    {"number": 2, "name": "Aerobics", "id": "idle-loop-aerobics", "is_free": False, "duration": 8.51},
    {"number": 3, "name": "Air Guitar", "id": "idle-guitar", "is_free": True, "duration": 13.23},
    {"number": 4, "name": "Amused", "id": "emote-laughing2", "is_free": False, "duration": 5.06},
    {"number": 5, "name": "Angry", "id": "emoji-angry", "is_free": True, "duration": 5.76},
    {"number": 6, "name": "Anime Dance", "id": "dance-anime", "is_free": True, "duration": 8.47},
    {"number": 7, "name": "Annoyed", "id": "idle-loop-annoyed", "is_free": False, "duration": 17.06},
    {"number": 8, "name": "Arrogance", "id": "emoji-arrogance", "is_free": False, "duration": 6.87},
    {"number": 9, "name": "Astronaut", "id": "emote-astronaut", "is_free": True, "duration": 13.79},
    {"number": 10, "name": "At Attention", "id": "emote-salute", "is_free": True, "duration": 3.00},
    {"number": 11, "name": "Attention", "id": "emote-attention", "is_free": False, "duration": 4.40},
    {"number": 12, "name": "Attentive", "id": "idle_layingdown", "is_free": False, "duration": 24.59},
    {"number": 13, "name": "Blast Off", "id": "emote-disappear", "is_free": False, "duration": 6.20},
    {"number": 14, "name": "Blowing Kisses", "id": "emote-blowkisses", "is_free": False, "duration": 5.98},
    {"number": 15, "name": "Boo", "id": "emote-boo", "is_free": False, "duration": 4.50},
    {"number": 16, "name": "Boogie Swing", "id": "idle-dance-swinging", "is_free": False, "duration": 13.20},
    {"number": 17, "name": "Bow", "id": "emote-bow", "is_free": True, "duration": 3.34},
    {"number": 18, "name": "Boxer", "id": "emote-boxer", "is_free": True, "duration": 5.56},
    {"number": 19, "name": "Breakdance", "id": "dance-breakdance", "is_free": False, "duration": 17.62},
    {"number": 20, "name": "Bummed", "id": "idle-loop-sad", "is_free": False, "duration": 6.05},
    {"number": 21, "name": "Bunny Hop", "id": "emote-bunnyhop", "is_free": False, "duration": 12.38},
    {"number": 22, "name": "Casting!", "id": "fishing-cast", "is_free": True, "duration": 2.82},
    {"number": 23, "name": "Casual Dance", "id": "idle-dance-casual", "is_free": True, "duration": 9.08},
    {"number": 24, "name": "Celebration Step", "id": "emote-celebrationstep", "is_free": True, "duration": 3.35},
    {"number": 25, "name": "Charging", "id": "emote-charging", "is_free": True, "duration": 8.03},
    {"number": 26, "name": "Cheer", "id": "dance-cheerleader", "is_free": True, "duration": 17.93},
    {"number": 27, "name": "Chillin'", "id": "idle-loop-happy", "is_free": False, "duration": 18.80},
    {"number": 28, "name": "Clap", "id": "emoji-clapping", "is_free": False, "duration": 2.16},
    {"number": 29, "name": "Clumsy", "id": "emote-fail2", "is_free": False, "duration": 6.48},
    {"number": 30, "name": "Cold", "id": "emote-cold", "is_free": False, "duration": 3.66},
    {"number": 31, "name": "Collapse", "id": "emote-death2", "is_free": False, "duration": 4.86},
    {"number": 32, "name": "Confusion", "id": "emote-confused", "is_free": True, "duration": 8.58},
    {"number": 33, "name": "Cozy Nap", "id": "idle-floorsleeping", "is_free": False, "duration": 13.94},
    {"number": 34, "name": "Creepy puppet", "id": "dance-creepypuppet", "is_free": True, "duration": 6.42},
    {"number": 35, "name": "Creepycute", "id": "emote-creepycute", "is_free": True, "duration": 7.90},
    {"number": 36, "name": "Crouch", "id": "idle-crouched", "is_free": False, "duration": 28.27},
    {"number": 37, "name": "Cursing Emote", "id": "emoji-cursing", "is_free": True, "duration": 2.38},
    {"number": 38, "name": "Curtsy", "id": "emote-curtsy", "is_free": True, "duration": 2.43},
    {"number": 39, "name": "Cute", "id": "emote-cute", "is_free": True, "duration": 6.17},
    {"number": 40, "name": "Cute Salute", "id": "emote-cutesalute", "is_free": True, "duration": 3.00},
    {"number": 41, "name": "Cutey", "id": "emote-cutey", "is_free": True, "duration": 3.26},
    {"number": 42, "name": "Dab", "id": "emote-dab", "is_free": False, "duration": 2.72},
    {"number": 43, "name": "Dance Zombie", "id": "dance-zombie", "is_free": True, "duration": 12.92},
    {"number": 44, "name": "dance-anime3", "id": "dance-anime3", "is_free": True, "duration": 12.37},
    {"number": 45, "name": "dance-kid", "id": "dance-kid", "is_free": True, "duration": 10.30},
    {"number": 46, "name": "dance-shuffle", "id": "dance-shuffle", "is_free": True, "duration": 9.05},
    {"number": 47, "name": "dance-tiktok1", "id": "dance-tiktok1", "is_free": True, "duration": 12.42},
    {"number": 48, "name": "dance-tiktok15", "id": "dance-tiktok15", "is_free": True, "duration": 16.11},
    {"number": 49, "name": "dance-tiktok16", "id": "dance-tiktok16", "is_free": True, "duration": 11.02},
    {"number": 50, "name": "dance-tiktok3", "id": "dance-tiktok3", "is_free": True, "duration": 10.40},
    {"number": 51, "name": "dance-tiktok4", "id": "dance-tiktok4", "is_free": True, "duration": 15.00},
    {"number": 52, "name": "dance-tiktok5", "id": "dance-tiktok5", "is_free": True, "duration": 12.20},
    {"number": 53, "name": "dance-tiktok6", "id": "dance-tiktok6", "is_free": True, "duration": 11.99},
    {"number": 54, "name": "dance-tiktok7", "id": "dance-tiktok7", "is_free": True, "duration": 13.89},
    {"number": 55, "name": "Disco", "id": "emote-disco", "is_free": False, "duration": 5.37},
    {"number": 56, "name": "Ditzy Pose", "id": "emote-pose9", "is_free": True, "duration": 4.58},
    {"number": 57, "name": "Don't Start Now", "id": "dance-tiktok2", "is_free": True, "duration": 10.39},
    {"number": 58, "name": "Don't Touch Dance", "id": "dance-tiktok13", "is_free": True, "duration": 9.24},
    {"number": 59, "name": "Duck Walk", "id": "dance-duckwalk", "is_free": False, "duration": 11.75},
    {"number": 60, "name": "Elbow Bump", "id": "emote-elbowbump", "is_free": False, "duration": 3.80},
    {"number": 61, "name": "Embarrassed", "id": "emote-embarrassed", "is_free": False, "duration": 7.41},
    {"number": 62, "name": "emoji-shush", "id": "emoji-shush", "is_free": True, "duration": 3.40},
    {"number": 63, "name": "emote-armcannon", "id": "emote-armcannon", "is_free": True, "duration": 8.67},
    {"number": 64, "name": "emote-cartwheel", "id": "emote-cartwheel", "is_free": True, "duration": 7.94},
    {"number": 65, "name": "emote-confused2", "id": "emote-confused2", "is_free": True, "duration": 10.06},
    {"number": 66, "name": "emote-dinner", "id": "emote-dinner", "is_free": True, "duration": 14.25},
    {"number": 67, "name": "emote-dramatic", "id": "emote-dramatic", "is_free": True, "duration": 9.10},
    {"number": 68, "name": "emote-electrified", "id": "emote-electrified", "is_free": True, "duration": 5.29},
    {"number": 69, "name": "emote-fading", "id": "emote-fading", "is_free": True, "duration": 14.05},
    {"number": 70, "name": "emote-fail3", "id": "emote-fail3", "is_free": True, "duration": 7.06},
    {"number": 71, "name": "emote-fireworks", "id": "emote-fireworks", "is_free": True, "duration": 13.15},
    {"number": 72, "name": "emote-flirt", "id": "emote-flirt", "is_free": True, "duration": 7.95},
    {"number": 73, "name": "emote-gooey", "id": "emote-gooey", "is_free": True, "duration": 5.82},
    {"number": 74, "name": "emote-handwalk", "id": "emote-handwalk", "is_free": True, "duration": 7.77},
    {"number": 75, "name": "emote-holding-hot-cocoa", "id": "emote-holding-hot-cocoa", "is_free": False, "duration": 3.87},
    {"number": 76, "name": "emote-hopscotch", "id": "emote-hopscotch", "is_free": True, "duration": 5.84},
    {"number": 77, "name": "emote-juggling", "id": "emote-juggling", "is_free": True, "duration": 5.83},
    {"number": 78, "name": "emote-kissing-passionate", "id": "emote-kissing-passionate", "is_free": True, "duration": 10.47},
    {"number": 79, "name": "emote-mittens", "id": "emote-mittens", "is_free": False, "duration": 3.17},
    {"number": 80, "name": "emote-oops", "id": "emote-oops", "is_free": True, "duration": 8.02},
    {"number": 81, "name": "emote-opera", "id": "emote-opera", "is_free": True, "duration": 5.76},
    {"number": 82, "name": "emote-outfit", "id": "emote-outfit", "is_free": True, "duration": 13.20},
    {"number": 83, "name": "emote-outfit2", "id": "emote-outfit2", "is_free": True, "duration": 11.94},
    {"number": 84, "name": "emote-pose11", "id": "emote-pose11", "is_free": True, "duration": 5.11},
    {"number": 85, "name": "emote-pose12", "id": "emote-pose12", "is_free": True, "duration": 5.81},
    {"number": 86, "name": "emote-pose13", "id": "emote-pose13", "is_free": True, "duration": 6.39},
    {"number": 87, "name": "emote-pose2", "id": "emote-pose2", "is_free": True, "duration": 7.20},
    {"number": 88, "name": "emote-receive-disappointed", "id": "emote-receive-disappointed", "is_free": True, "duration": 7.14},
    {"number": 89, "name": "emote-receive-happy", "id": "emote-receive-happy", "is_free": True, "duration": 5.94},
    {"number": 90, "name": "emote-runhop", "id": "emote-runhop", "is_free": True, "duration": 8.72},
    {"number": 91, "name": "emote-sheephop", "id": "emote-sheephop", "is_free": True, "duration": 3.78},
    {"number": 92, "name": "emote-shocked", "id": "emote-shocked", "is_free": True, "duration": 5.59},
    {"number": 93, "name": "emote-surf", "id": "emote-surf", "is_free": True, "duration": 19.01},
    {"number": 94, "name": "emote-theatrical-test", "id": "emote-theatrical-test", "is_free": True, "duration": 10.86},
    {"number": 95, "name": "emote-thief", "id": "emote-thief", "is_free": True, "duration": 6.89},
    {"number": 96, "name": "emote-twitched", "id": "emote-twitched", "is_free": True, "duration": 9.61},
    {"number": 97, "name": "emote-wavey", "id": "emote-wavey", "is_free": True, "duration": 12.60},
    {"number": 98, "name": "Energy Ball", "id": "emote-energyball", "is_free": True, "duration": 7.58},
    {"number": 99, "name": "Enthused", "id": "idle-enthusiastic", "is_free": True, "duration": 15.94},
    {"number": 100, "name": "Exasperated", "id": "emote-exasperated", "is_free": False, "duration": 2.37},
    {"number": 101, "name": "Eyeroll", "id": "emoji-eyeroll", "is_free": False, "duration": 3.02},
    {"number": 102, "name": "Face Palm", "id": "emote-exasperatedb", "is_free": True, "duration": 2.72},
    {"number": 103, "name": "Faint", "id": "emote-fainting", "is_free": False, "duration": 18.42},
    {"number": 104, "name": "Faint Drop", "id": "emote-deathdrop", "is_free": False, "duration": 3.76},
    {"number": 105, "name": "Fairy Float", "id": "idle-floating", "is_free": True, "duration": 27.60},
    {"number": 106, "name": "Fairy Twirl", "id": "emote-looping", "is_free": True, "duration": 9.89},
    {"number": 107, "name": "Fall", "id": "emote-fail1", "is_free": False, "duration": 5.62},
    {"number": 108, "name": "Falling Apart", "id": "emote-apart", "is_free": False, "duration": 4.81},
    {"number": 109, "name": "Fashionista", "id": "emote-fashionista", "is_free": True, "duration": 5.61},
    {"number": 110, "name": "Feel The Beat", "id": "idle-dance-headbobbing", "is_free": False, "duration": 25.37},
    {"number": 111, "name": "Fighter idle", "id": "idle-fighter", "is_free": False, "duration": 17.19},
    {"number": 112, "name": "Fireball Lunge", "id": "emoji-hadoken", "is_free": False, "duration": 2.72},
    {"number": 113, "name": "Flex", "id": "emoji-flex", "is_free": True, "duration": 2.10},
    {"number": 114, "name": "Flirty Wave", "id": "emote-lust", "is_free": True, "duration": 4.66},
    {"number": 115, "name": "Float", "id": "emote-float", "is_free": True, "duration": 9.00},
    {"number": 116, "name": "Floss", "id": "dance-floss", "is_free": False, "duration": 21.33},
    {"number": 117, "name": "Frog", "id": "emote-frog", "is_free": True, "duration": 14.55},
    {"number": 118, "name": "Frolic ", "id": "emote-frollicking", "is_free": False, "duration": 3.70},
    {"number": 119, "name": "Fruity Dance", "id": "dance-fruity", "is_free": True, "duration": 18.25},
    {"number": 120, "name": "Frustrated", "id": "emote-frustrated", "is_free": False, "duration": 5.58},
    {"number": 121, "name": "Gangnam Style", "id": "emote-gangnam", "is_free": False, "duration": 7.28},
    {"number": 122, "name": "Gasp", "id": "emoji-scared", "is_free": False, "duration": 3.01},
    {"number": 123, "name": "Ghost", "id": "emoji-ghost", "is_free": False, "duration": 3.47},
    {"number": 124, "name": "Ghost Float", "id": "emote-ghost-idle", "is_free": False, "duration": 19.57},
    {"number": 125, "name": "Give Up", "id": "emoji-give-up", "is_free": False, "duration": 5.41},
    {"number": 126, "name": "Graceful", "id": "emote-graceful", "is_free": False, "duration": 3.75},
    {"number": 127, "name": "Gravity", "id": "emote-gravity", "is_free": True, "duration": 8.96},
    {"number": 128, "name": "Greedy Emote", "id": "emote-greedy", "is_free": True, "duration": 4.64},
    {"number": 129, "name": "Hands in the Air", "id": "dance-handsup", "is_free": False, "duration": 22.28},
    {"number": 130, "name": "Handstand", "id": "emote-handstand", "is_free": False, "duration": 4.02},
    {"number": 131, "name": "Happy", "id": "emote-happy", "is_free": False, "duration": 3.48},
    {"number": 132, "name": "Harlem Shake", "id": "emote-harlemshake", "is_free": False, "duration": 13.56},
    {"number": 133, "name": "Head Blowup", "id": "emote-headblowup", "is_free": True, "duration": 11.67},
    {"number": 134, "name": "Headball", "id": "emote-headball", "is_free": False, "duration": 10.07},
    {"number": 135, "name": "Heart Eyes", "id": "emote-hearteyes", "is_free": True, "duration": 4.03},
    {"number": 136, "name": "Heart Fingers", "id": "emote-heartfingers", "is_free": True, "duration": 4.00},
    {"number": 137, "name": "Heart Shape", "id": "emote-heartshape", "is_free": False, "duration": 6.23},
    {"number": 138, "name": "Hello", "id": "emote-hello", "is_free": True, "duration": 2.73},
    {"number": 139, "name": "Hero Entrance", "id": "emote-hero", "is_free": False, "duration": 5.00},
    {"number": 140, "name": "Hero Pose", "id": "idle-hero", "is_free": False, "duration": 21.88},
    {"number": 141, "name": "Hip Hop Dance", "id": "dance-hiphop", "is_free": True, "duration": 27.59},
    {"number": 142, "name": "Hip Shake", "id": "dance-hipshake", "is_free": True, "duration": 13.38},
    {"number": 143, "name": "Home Run!", "id": "emote-baseball", "is_free": False, "duration": 7.25},
    {"number": 144, "name": "Hug", "id": "emote-hug", "is_free": False, "duration": 3.50},
    {"number": 145, "name": "Hug Yourself", "id": "emote-hugyourself", "is_free": False, "duration": 4.99},
    {"number": 146, "name": "Hyped", "id": "emote-hyped", "is_free": True, "duration": 7.49},
    {"number": 147, "name": "I Believe I Can Fly", "id": "emote-wings", "is_free": False, "duration": 13.13},
    {"number": 148, "name": "Ice Cream Dance", "id": "dance-icecream", "is_free": True, "duration": 14.77},
    {"number": 149, "name": "Ice Skating", "id": "emote-iceskating", "is_free": True, "duration": 7.30},
    {"number": 150, "name": "idle-cold", "id": "idle-cold", "is_free": True, "duration": 17.71},
    {"number": 151, "name": "idle-dance-tiktok6", "id": "idle-dance-tiktok6", "is_free": True, "duration": 9.73},
    {"number": 152, "name": "idle-headless", "id": "idle-headless", "is_free": True, "duration": 41.80},
    {"number": 153, "name": "idle-phone", "id": "idle-phone", "is_free": False, "duration": 31.36},
    {"number": 154, "name": "idle-space", "id": "idle-space", "is_free": True, "duration": 37.78},
    {"number": 155, "name": "idle_tough", "id": "idle_tough", "is_free": True, "duration": 28.64},
    {"number": 156, "name": "Ignition Boost", "id": "hcc-jetpack", "is_free": False, "duration": 27.45},
    {"number": 157, "name": "Imaginary Jetpack", "id": "emote-jetpack", "is_free": False, "duration": 16.76},
    {"number": 158, "name": "Irritated", "id": "idle-angry", "is_free": False, "duration": 25.43},
    {"number": 159, "name": "Jinglebell", "id": "dance-jinglebell", "is_free": True, "duration": 11.00},
    {"number": 160, "name": "Judo Chop", "id": "emote-judochop", "is_free": False, "duration": 2.43},
    {"number": 161, "name": "Jump", "id": "emote-jumpb", "is_free": False, "duration": 3.58},
    {"number": 162, "name": "K-Pop Dance", "id": "dance-blackpink", "is_free": True, "duration": 7.15},
    {"number": 163, "name": "Karate", "id": "dance-martial-artist", "is_free": False, "duration": 13.28},
    {"number": 164, "name": "Karma Dance", "id": "dance-wild", "is_free": True, "duration": 16.25},
    {"number": 165, "name": "Kawaii", "id": "dance-kawai", "is_free": True, "duration": 10.29},
    {"number": 166, "name": "KawaiiGoGo", "id": "emote-kawaiigogo", "is_free": False, "duration": 10.00},
    {"number": 167, "name": "Kiss", "id": "emote-kiss", "is_free": True, "duration": 2.39},
    {"number": 168, "name": "Laid Back", "id": "sit-open", "is_free": False, "duration": 26.03},
    {"number": 169, "name": "Landing a Fish!", "id": "fishing-pull", "is_free": True, "duration": 2.81},
    {"number": 170, "name": "Laugh", "id": "emote-laughing", "is_free": True, "duration": 2.69},
    {"number": 171, "name": "Laugh", "id": "emote-lagughing", "is_free": False, "duration": 1.13},
    {"number": 172, "name": "Launch", "id": "emote-launch", "is_free": True, "duration": 10.88},
    {"number": 173, "name": "Let's Go Shopping", "id": "dance-shoppingcart", "is_free": True, "duration": 4.32},
    {"number": 174, "name": "Level Up!", "id": "emote-levelup", "is_free": False, "duration": 6.05},
    {"number": 175, "name": "Levitate", "id": "emoji-halo", "is_free": False, "duration": 5.84},
    {"number": 176, "name": "Lying", "id": "emoji-lying", "is_free": False, "duration": 6.31},
    {"number": 177, "name": "Macarena", "id": "dance-macarena", "is_free": True, "duration": 12.21},
    {"number": 178, "name": "Magnetic", "id": "dance-tiktok14", "is_free": True, "duration": 11.20},
    {"number": 179, "name": "Maniac", "id": "emote-maniac", "is_free": True, "duration": 4.91},
    {"number": 180, "name": "Mind Blown", "id": "emoji-mind-blown", "is_free": False, "duration": 2.40},
    {"number": 181, "name": "mining-fail", "id": "mining-fail", "is_free": True, "duration": 3.41},
    {"number": 182, "name": "mining-mine", "id": "mining-mine", "is_free": True, "duration": 5.02},
    {"number": 183, "name": "mining-success", "id": "mining-success", "is_free": True, "duration": 3.11},
    {"number": 184, "name": "Model", "id": "emote-model", "is_free": True, "duration": 6.49},
    {"number": 185, "name": "Monster Fail", "id": "emote-monster_fail", "is_free": False, "duration": 4.63},
    {"number": 186, "name": "Moonlit Howl", "id": "emote-howl", "is_free": True, "duration": 8.10},
    {"number": 187, "name": "Moonwalk", "id": "emote-gordonshuffle", "is_free": False, "duration": 8.05},
    {"number": 188, "name": "Muscle pose", "id": "emote-pose4", "is_free": True, "duration": 6.08},
    {"number": 189, "name": "Naughty", "id": "emoji-naughty", "is_free": False, "duration": 4.28},
    {"number": 190, "name": "Nervous", "id": "idle-nervous", "is_free": True, "duration": 21.71},
    {"number": 191, "name": "Night Fever", "id": "emote-nightfever", "is_free": False, "duration": 5.49},
    {"number": 192, "name": "Ninja Run", "id": "emote-ninjarun", "is_free": False, "duration": 4.75},
    {"number": 193, "name": "No", "id": "emote-no", "is_free": True, "duration": 2.70},
    {"number": 194, "name": "Nocturnal Howl", "id": "idle-howl", "is_free": True, "duration": 48.62},
    {"number": 195, "name": "Now We Wait...", "id": "fishing-idle", "is_free": True, "duration": 17.87},
    {"number": 196, "name": "Orange Juice Dance", "id": "dance-orangejustice", "is_free": False, "duration": 6.48},
    {"number": 197, "name": "Panic", "id": "emote-panic", "is_free": False, "duration": 2.85},
    {"number": 198, "name": "Party Time!", "id": "emote-celebrate", "is_free": True, "duration": 4.35},
    {"number": 199, "name": "Peace", "id": "emote-peace", "is_free": False, "duration": 5.76},
    {"number": 200, "name": "Peekaboo!", "id": "emote-peekaboo", "is_free": False, "duration": 3.63},
    {"number": 201, "name": "Penguin dance", "id": "dance-pinguin", "is_free": True, "duration": 11.58},
    {"number": 202, "name": "Penny's Dance", "id": "dance-pennywise", "is_free": True, "duration": 1.21},
    {"number": 203, "name": "Point", "id": "emoji-there", "is_free": False, "duration": 2.06},
    {"number": 204, "name": "Poke dance", "id": "dance-tiktok12", "is_free": True, "duration": 14.85},
    {"number": 205, "name": "Ponder", "id": "idle-lookup", "is_free": False, "duration": 22.34},
    {"number": 206, "name": "Pose 1", "id": "emote-pose1", "is_free": True, "duration": 2.83},
    {"number": 207, "name": "Pose 10", "id": "emote-pose10", "is_free": True, "duration": 3.99},
    {"number": 208, "name": "Pose 3", "id": "emote-pose3", "is_free": True, "duration": 5.11},
    {"number": 209, "name": "Pose 5", "id": "emote-pose5", "is_free": True, "duration": 4.62},
    {"number": 210, "name": "Pose 7", "id": "emote-pose7", "is_free": True, "duration": 4.66},
    {"number": 211, "name": "Pose 8", "id": "emote-pose8", "is_free": True, "duration": 4.81},
    {"number": 212, "name": "Posh", "id": "idle-posh", "is_free": False, "duration": 21.85},
    {"number": 213, "name": "Pouty Face", "id": "idle-sad", "is_free": False, "duration": 24.38},
    {"number": 214, "name": "Pray", "id": "emoji-pray", "is_free": False, "duration": 4.50},
    {"number": 215, "name": "Proposing", "id": "emote-proposing", "is_free": False, "duration": 4.28},
    {"number": 216, "name": "Punch", "id": "emoji-punch", "is_free": False, "duration": 1.76},
    {"number": 217, "name": "Punk Guitar", "id": "emote-punkguitar", "is_free": True, "duration": 9.37},
    {"number": 218, "name": "Puppet", "id": "emote-puppet", "is_free": False, "duration": 16.33},
    {"number": 219, "name": "Push it", "id": "dance-employee", "is_free": True, "duration": 8.00},
    {"number": 220, "name": "Push Ups", "id": "dance-aerobics", "is_free": False, "duration": 8.80},
    {"number": 221, "name": "Rainbow", "id": "emote-rainbow", "is_free": False, "duration": 2.81},
    {"number": 222, "name": "Raise The Roof", "id": "emoji-celebrate", "is_free": True, "duration": 3.41},
    {"number": 223, "name": "Relaxed", "id": "idle_layingdown2", "is_free": False, "duration": 21.55},
    {"number": 224, "name": "Relaxed", "id": "sit-relaxed", "is_free": False, "duration": 29.89},
    {"number": 225, "name": "Relaxing", "id": "idle-floorsleeping2", "is_free": False, "duration": 17.25},
    {"number": 226, "name": "Repose", "id": "emote-repose", "is_free": False, "duration": 1.12},
    {"number": 227, "name": "Rest", "id": "sit-idle-cute", "is_free": False, "duration": 17.06},
    {"number": 228, "name": "Revival", "id": "emote-death", "is_free": False, "duration": 6.62},
    {"number": 229, "name": "Ring on It", "id": "dance-singleladies", "is_free": False, "duration": 21.19},
    {"number": 230, "name": "Robot", "id": "emote-robot", "is_free": False, "duration": 7.61},
    {"number": 231, "name": "Robotic", "id": "dance-robotic", "is_free": False, "duration": 17.81},
    {"number": 232, "name": "Rock Out", "id": "dance-metal", "is_free": False, "duration": 15.08},
    {"number": 233, "name": "ROFL!", "id": "emote-rofl", "is_free": False, "duration": 6.31},
    {"number": 234, "name": "Roll", "id": "emote-roll", "is_free": False, "duration": 3.56},
    {"number": 235, "name": "Rope Pull", "id": "emote-ropepull", "is_free": False, "duration": 8.77},
    {"number": 236, "name": "run-vertical", "id": "run-vertical", "is_free": False, "duration": 3.86},
    {"number": 237, "name": "Russian Dance", "id": "dance-russian", "is_free": True, "duration": 10.25},
    {"number": 238, "name": "Sad", "id": "emote-sad", "is_free": True, "duration": 5.41},
    {"number": 239, "name": "Savage Dance", "id": "dance-tiktok8", "is_free": True, "duration": 10.94},
    {"number": 240, "name": "Scritchy", "id": "idle-wild", "is_free": True, "duration": 26.42},
    {"number": 241, "name": "Secret Handshake", "id": "emote-secrethandshake", "is_free": False, "duration": 3.88},
    {"number": 242, "name": "Sexy dance", "id": "dance-sexy", "is_free": False, "duration": 12.31},
    {"number": 243, "name": "Shrink", "id": "emote-shrink", "is_free": False, "duration": 8.74},
    {"number": 244, "name": "Shy", "id": "emote-shy", "is_free": True, "duration": 4.48},
    {"number": 245, "name": "Shy", "id": "idle-loop-shy", "is_free": False, "duration": 16.47},
    {"number": 246, "name": "Sick", "id": "emoji-sick", "is_free": False, "duration": 5.07},
    {"number": 247, "name": "Singing", "id": "idle_singing", "is_free": True, "duration": 10.26},
    {"number": 248, "name": "Sit", "id": "idle-loop-sitfloor", "is_free": True, "duration": 22.32},
    {"number": 249, "name": "sit-chair", "id": "sit-chair", "is_free": True, "duration": 3.30},
    {"number": 250, "name": "Slap", "id": "emote-slap", "is_free": False, "duration": 2.72},
    {"number": 251, "name": "Sleepy", "id": "idle-sleep", "is_free": False, "duration": 22.62},
    {"number": 252, "name": "Sleepy", "id": "idle-loop-tired", "is_free": False, "duration": 21.96},
    {"number": 253, "name": "Sleigh", "id": "emote-sleigh", "is_free": True, "duration": 11.33},
    {"number": 254, "name": "Smirk", "id": "emoji-smirking", "is_free": False, "duration": 4.82},
    {"number": 255, "name": "Smoothwalk", "id": "dance-smoothwalk", "is_free": False, "duration": 6.69},
    {"number": 256, "name": "Snake", "id": "emote-snake", "is_free": True, "duration": 5.26},
    {"number": 257, "name": "Sneeze", "id": "emoji-sneeze", "is_free": False, "duration": 3.00},
    {"number": 258, "name": "Snow Angel", "id": "emote-snowangel", "is_free": True, "duration": 6.22},
    {"number": 259, "name": "Snowball Fight!", "id": "emote-snowball", "is_free": True, "duration": 5.23},
    {"number": 260, "name": "Sob", "id": "emoji-crying", "is_free": False, "duration": 3.70},
    {"number": 261, "name": "Splits Drop", "id": "emote-splitsdrop", "is_free": False, "duration": 4.47},
    {"number": 262, "name": "Star gazing", "id": "emote-stargaze", "is_free": False, "duration": 1.13},
    {"number": 263, "name": "Stargazing", "id": "emote-stargazer", "is_free": True, "duration": 7.93},
    {"number": 264, "name": "Stinky", "id": "emoji-poop", "is_free": False, "duration": 4.80},
    {"number": 265, "name": "Stunned", "id": "emoji-dizzy", "is_free": False, "duration": 4.05},
    {"number": 266, "name": "Sumo Fight", "id": "emote-sumo", "is_free": False, "duration": 10.87},
    {"number": 267, "name": "Super Kick", "id": "emote-kicking", "is_free": False, "duration": 4.87},
    {"number": 268, "name": "Super Punch", "id": "emote-superpunch", "is_free": False, "duration": 3.75},
    {"number": 269, "name": "Super Run", "id": "emote-superrun", "is_free": False, "duration": 6.27},
    {"number": 270, "name": "Superpose", "id": "emote-superpose", "is_free": True, "duration": 4.53},
    {"number": 271, "name": "SurpriseBig", "id": "emote-pose6", "is_free": True, "duration": 5.38},
    {"number": 272, "name": "Sweating", "id": "emote-hot", "is_free": True, "duration": 4.35},
    {"number": 273, "name": "Sweet Smooch", "id": "emote-kissing", "is_free": False, "duration": 5.00},
    {"number": 274, "name": "Swordfight", "id": "emote-swordfight", "is_free": True, "duration": 5.91},
    {"number": 275, "name": "Tap Dance", "id": "emote-tapdance", "is_free": False, "duration": 11.06},
    {"number": 276, "name": "Tap Loop", "id": "idle-loop-tapdance", "is_free": False, "duration": 6.26},
    {"number": 277, "name": "Telekinesis", "id": "emote-telekinesis", "is_free": True, "duration": 10.49},
    {"number": 278, "name": "Teleporting", "id": "emote-teleporting", "is_free": True, "duration": 11.77},
    {"number": 279, "name": "The Wave", "id": "emote-wave", "is_free": True, "duration": 2.69},
    {"number": 280, "name": "Theatrical", "id": "emote-theatrical", "is_free": False, "duration": 8.59},
    {"number": 281, "name": "Think", "id": "emote-think", "is_free": False, "duration": 3.69},
    {"number": 282, "name": "This Is For You", "id": "emote-gift", "is_free": True, "duration": 5.80},
    {"number": 283, "name": "Thumb Suck", "id": "emote-suckthumb", "is_free": False, "duration": 4.19},
    {"number": 284, "name": "Thumbs Up", "id": "emoji-thumbsup", "is_free": True, "duration": 2.70},
    {"number": 285, "name": "TikTok Dance 10", "id": "dance-tiktok10", "is_free": True, "duration": 8.23},
    {"number": 286, "name": "TikTok Dance 4", "id": "idle-dance-tiktok4", "is_free": True, "duration": 15.50},
    {"number": 287, "name": "TikTok Dance 9", "id": "dance-tiktok9", "is_free": True, "duration": 11.89},
    {"number": 288, "name": "Tiktok7", "id": "idle-dance-tiktok7", "is_free": False, "duration": 12.96},
    {"number": 289, "name": "TimeJump", "id": "emote-timejump", "is_free": True, "duration": 4.01},
    {"number": 290, "name": "Tired", "id": "emote-tired", "is_free": True, "duration": 4.61},
    {"number": 291, "name": "Toilet", "id": "idle-toilet", "is_free": True, "duration": 32.17},
    {"number": 292, "name": "Touch", "id": "dance-touch", "is_free": True, "duration": 11.70},
    {"number": 293, "name": "Trampoline", "id": "emote-trampoline", "is_free": True, "duration": 6.11},
    {"number": 294, "name": "Tummy Ache", "id": "emoji-gagging", "is_free": True, "duration": 5.50},
    {"number": 295, "name": "Uhmmm", "id": "emote-thought", "is_free": False, "duration": 27.43},
    {"number": 296, "name": "UwU", "id": "idle-uwu", "is_free": True, "duration": 24.76},
    {"number": 297, "name": "Vogue Hands", "id": "dance-voguehands", "is_free": False, "duration": 9.15},
    {"number": 298, "name": "Wait", "id": "dance-wait", "is_free": False, "duration": 9.92},
    {"number": 299, "name": "walk-vertical", "id": "walk-vertical", "is_free": False, "duration": 4.18},
    {"number": 300, "name": "We Have a Strike!", "id": "fishing-pull-small", "is_free": True, "duration": 3.67},
    {"number": 301, "name": "Weird Dance", "id": "dance-weird", "is_free": True, "duration": 21.56},
    {"number": 302, "name": "Wop Dance", "id": "dance-tiktok11", "is_free": True, "duration": 11.00},
    {"number": 303, "name": "Wrong Dance", "id": "dance-wrong", "is_free": True, "duration": 12.42},
    {"number": 304, "name": "Yes", "id": "emote-yes", "is_free": True, "duration": 2.57},
    {"number": 305, "name": "Yoga Flow", "id": "dance-spiritual", "is_free": False, "duration": 15.80},
    {"number": 306, "name": "Zombie", "id": "idle_zombie", "is_free": False, "duration": 28.75},
    {"number": 307, "name": "Zombie Run", "id": "emote-zombierun", "is_free": False, "duration": 9.18}
]