# -*- coding: utf-8 -*-
"""
emotes_dict.py — Komplette Highrise Emote-Liste (307 Emotes, 303 eindeutige + 6 Aliase = 309)
Automatisch generiert aus emotes_complete.py
Format: EMOTES[name] = emote_id, EMOTE_BY_NUM[num] = name
"""

# ── Komplette Emote-Liste ───────────────────────────────────
# Name (lowercase) → Highrise Emote ID
# Bei Duplikaten (gleicher Name, verschiedene IDs) wird der freie Emote bevorzugt.
# Aliase: Alte Kurznamen zeigen auf den gleichen Emote (z.B. "wave" → "the wave").
EMOTES: dict[str, str] = {
    "advanced shy": "emote-shy2",
    "aerobics": "idle-loop-aerobics",
    "air guitar": "idle-guitar",
    "amused": "emote-laughing2",
    "angry": "emoji-angry",
    "anime dance": "dance-anime",
    "annoyed": "idle-loop-annoyed",
    "arrogance": "emoji-arrogance",
    "astronaut": "emote-astronaut",
    "at attention": "emote-salute",
    "attention": "emote-attention",
    "attentive": "idle_layingdown",
    "blast off": "emote-disappear",
    "blowing kisses": "emote-blowkisses",
    "boo": "emote-boo",
    "boogie swing": "idle-dance-swinging",
    "bow": "emote-bow",
    "boxer": "emote-boxer",
    "breakdance": "dance-breakdance",
    "bummed": "idle-loop-sad",
    "bunny hop": "emote-bunnyhop",
    "casting!": "fishing-cast",
    "casual dance": "idle-dance-casual",
    "celebration step": "emote-celebrationstep",
    "charging": "emote-charging",
    "cheer": "dance-cheerleader",
    "chillin'": "idle-loop-happy",
    "clap": "emoji-clapping",
    "clumsy": "emote-fail2",
    "cold": "emote-cold",
    "collapse": "emote-death2",
    "confusion": "emote-confused",
    "cozy nap": "idle-floorsleeping",
    "creepy puppet": "dance-creepypuppet",
    "creepycute": "emote-creepycute",
    "crouch": "idle-crouched",
    "cursing emote": "emoji-cursing",
    "curtsy": "emote-curtsy",
    "cute": "emote-cute",
    "cute salute": "emote-cutesalute",
    "cutey": "emote-cutey",
    "dab": "emote-dab",
    "dance zombie": "dance-zombie",
    "dance-anime3": "dance-anime3",
    "dance-kid": "dance-kid",
    "dance-shuffle": "dance-shuffle",
    "dance-tiktok1": "dance-tiktok1",
    "dance-tiktok15": "dance-tiktok15",
    "dance-tiktok16": "dance-tiktok16",
    "dance-tiktok3": "dance-tiktok3",
    "dance-tiktok4": "dance-tiktok4",
    "dance-tiktok5": "dance-tiktok5",
    "dance-tiktok6": "dance-tiktok6",
    "dance-tiktok7": "dance-tiktok7",
    "disco": "emote-disco",
    "ditzy pose": "emote-pose9",
    "don't start now": "dance-tiktok2",
    "don't touch dance": "dance-tiktok13",
    "duck walk": "dance-duckwalk",
    "elbow bump": "emote-elbowbump",
    "embarrassed": "emote-embarrassed",
    "emoji-shush": "emoji-shush",
    "emote-armcannon": "emote-armcannon",
    "emote-cartwheel": "emote-cartwheel",
    "emote-confused2": "emote-confused2",
    "emote-dinner": "emote-dinner",
    "emote-dramatic": "emote-dramatic",
    "emote-electrified": "emote-electrified",
    "emote-fading": "emote-fading",
    "emote-fail3": "emote-fail3",
    "emote-fireworks": "emote-fireworks",
    "emote-flirt": "emote-flirt",
    "emote-gooey": "emote-gooey",
    "emote-handwalk": "emote-handwalk",
    "emote-holding-hot-cocoa": "emote-holding-hot-cocoa",
    "emote-hopscotch": "emote-hopscotch",
    "emote-juggling": "emote-juggling",
    "emote-kissing-passionate": "emote-kissing-passionate",
    "emote-mittens": "emote-mittens",
    "emote-oops": "emote-oops",
    "emote-opera": "emote-opera",
    "emote-outfit": "emote-outfit",
    "emote-outfit2": "emote-outfit2",
    "emote-pose11": "emote-pose11",
    "emote-pose12": "emote-pose12",
    "emote-pose13": "emote-pose13",
    "emote-pose2": "emote-pose2",
    "emote-receive-disappointed": "emote-receive-disappointed",
    "emote-receive-happy": "emote-receive-happy",
    "emote-runhop": "emote-runhop",
    "emote-sheephop": "emote-sheephop",
    "emote-shocked": "emote-shocked",
    "emote-surf": "emote-surf",
    "emote-theatrical-test": "emote-theatrical-test",
    "emote-thief": "emote-thief",
    "emote-twitched": "emote-twitched",
    "emote-wavey": "emote-wavey",
    "energy ball": "emote-energyball",
    "enthused": "idle-enthusiastic",
    "exasperated": "emote-exasperated",
    "eyeroll": "emoji-eyeroll",
    "face palm": "emote-exasperatedb",
    "faint": "emote-fainting",
    "faint drop": "emote-deathdrop",
    "fairy float": "idle-floating",
    "fairy twirl": "emote-looping",
    "fall": "emote-fail1",
    "falling apart": "emote-apart",
    "fashionista": "emote-fashionista",
    "feel the beat": "idle-dance-headbobbing",
    "fighter idle": "idle-fighter",
    "fireball lunge": "emoji-hadoken",
    "flex": "emoji-flex",
    "flirty wave": "emote-lust",
    "float": "emote-float",
    "floss": "dance-floss",
    "frog": "emote-frog",
    "frolic ": "emote-frollicking",
    "fruity dance": "dance-fruity",
    "frustrated": "emote-frustrated",
    "gangnam style": "emote-gangnam",
    "gasp": "emoji-scared",
    "ghost": "emoji-ghost",
    "ghost float": "emote-ghost-idle",
    "give up": "emoji-give-up",
    "graceful": "emote-graceful",
    "gravity": "emote-gravity",
    "greedy emote": "emote-greedy",
    "hands in the air": "dance-handsup",
    "handstand": "emote-handstand",
    "happy": "emote-happy",
    "harlem shake": "emote-harlemshake",
    "head blowup": "emote-headblowup",
    "headball": "emote-headball",
    "heart eyes": "emote-hearteyes",
    "heart fingers": "emote-heartfingers",
    "heart shape": "emote-heartshape",
    "hello": "emote-hello",
    "hero entrance": "emote-hero",
    "hero pose": "idle-hero",
    "hip hop dance": "dance-hiphop",
    "hip shake": "dance-hipshake",
    "home run!": "emote-baseball",
    "hug": "emote-hug",
    "hug yourself": "emote-hugyourself",
    "hyped": "emote-hyped",
    "i believe i can fly": "emote-wings",
    "ice cream dance": "dance-icecream",
    "ice skating": "emote-iceskating",
    "idle-cold": "idle-cold",
    "idle-dance-tiktok6": "idle-dance-tiktok6",
    "idle-headless": "idle-headless",
    "idle-phone": "idle-phone",
    "idle-space": "idle-space",
    "idle_tough": "idle_tough",
    "ignition boost": "hcc-jetpack",
    "imaginary jetpack": "emote-jetpack",
    "irritated": "idle-angry",
    "jinglebell": "dance-jinglebell",
    "judo chop": "emote-judochop",
    "jump": "emote-jumpb",
    "k-pop dance": "dance-blackpink",
    "karate": "dance-martial-artist",
    "karma dance": "dance-wild",
    "kawaii": "dance-kawai",
    "kawaiigogo": "emote-kawaiigogo",
    "kiss": "emote-kiss",
    "laid back": "sit-open",
    "landing a fish!": "fishing-pull",
    "laugh": "emote-laughing",  # Alias → laugh
    "launch": "emote-launch",
    "let's go shopping": "dance-shoppingcart",
    "level up!": "emote-levelup",
    "levitate": "emoji-halo",
    "lying": "emoji-lying",
    "macarena": "dance-macarena",
    "magnetic": "dance-tiktok14",
    "maniac": "emote-maniac",
    "mind blown": "emoji-mind-blown",
    "mining-fail": "mining-fail",
    "mining-mine": "mining-mine",
    "mining-success": "mining-success",
    "model": "emote-model",
    "monster fail": "emote-monster_fail",
    "moonlit howl": "emote-howl",
    "moonwalk": "emote-gordonshuffle",
    "muscle pose": "emote-pose4",
    "naughty": "emoji-naughty",
    "nervous": "idle-nervous",
    "night fever": "emote-nightfever",
    "ninja run": "emote-ninjarun",
    "no": "emote-no",
    "nocturnal howl": "idle-howl",
    "now we wait...": "fishing-idle",
    "orange juice dance": "dance-orangejustice",
    "panic": "emote-panic",
    "party time!": "emote-celebrate",
    "peace": "emote-peace",
    "peekaboo!": "emote-peekaboo",
    "penguin dance": "dance-pinguin",
    "penny's dance": "dance-pennywise",
    "point": "emoji-there",
    "poke dance": "dance-tiktok12",
    "ponder": "idle-lookup",
    "pose 1": "emote-pose1",
    "pose 10": "emote-pose10",
    "pose 3": "emote-pose3",
    "pose 5": "emote-pose5",
    "pose 7": "emote-pose7",
    "pose 8": "emote-pose8",
    "posh": "idle-posh",
    "pouty face": "idle-sad",
    "pray": "emoji-pray",
    "proposing": "emote-proposing",
    "punch": "emoji-punch",
    "punk guitar": "emote-punkguitar",
    "puppet": "emote-puppet",
    "push it": "dance-employee",
    "push ups": "dance-aerobics",
    "rainbow": "emote-rainbow",
    "raise the roof": "emoji-celebrate",
    "relaxed": "idle_layingdown2",  # Alias → relaxed
    "relaxing": "idle-floorsleeping2",
    "repose": "emote-repose",
    "rest": "sit-idle-cute",
    "revival": "emote-death",
    "ring on it": "dance-singleladies",
    "robot": "emote-robot",
    "robotic": "dance-robotic",
    "rock out": "dance-metal",
    "rofl!": "emote-rofl",
    "roll": "emote-roll",
    "rope pull": "emote-ropepull",
    "run-vertical": "run-vertical",
    "russian dance": "dance-russian",
    "sad": "emote-sad",
    "savage dance": "dance-tiktok8",
    "scritchy": "idle-wild",
    "secret handshake": "emote-secrethandshake",
    "sexy dance": "dance-sexy",
    "shrink": "emote-shrink",
    "shy": "emote-shy",  # Alias → shy
    "sick": "emoji-sick",
    "singing": "idle_singing",
    "sit": "idle-loop-sitfloor",
    "sit-chair": "sit-chair",
    "slap": "emote-slap",
    "sleepy": "idle-sleep",  # Alias → sleepy
    "sleigh": "emote-sleigh",
    "smirk": "emoji-smirking",
    "smoothwalk": "dance-smoothwalk",
    "snake": "emote-snake",
    "sneeze": "emoji-sneeze",
    "snow angel": "emote-snowangel",
    "snowball fight!": "emote-snowball",
    "sob": "emoji-crying",
    "splits drop": "emote-splitsdrop",
    "star gazing": "emote-stargaze",
    "stargazing": "emote-stargazer",
    "stinky": "emoji-poop",
    "stunned": "emoji-dizzy",
    "sumo fight": "emote-sumo",
    "super kick": "emote-kicking",
    "super punch": "emote-superpunch",
    "super run": "emote-superrun",
    "superpose": "emote-superpose",
    "surprisebig": "emote-pose6",
    "sweating": "emote-hot",
    "sweet smooch": "emote-kissing",
    "swordfight": "emote-swordfight",
    "tap dance": "emote-tapdance",
    "tap loop": "idle-loop-tapdance",
    "telekinesis": "emote-telekinesis",
    "teleporting": "emote-teleporting",
    "the wave": "emote-wave",
    "theatrical": "emote-theatrical",
    "think": "emote-think",
    "this is for you": "emote-gift",
    "thumb suck": "emote-suckthumb",
    "thumbs up": "emoji-thumbsup",
    "tiktok dance 10": "dance-tiktok10",
    "tiktok dance 4": "idle-dance-tiktok4",
    "tiktok dance 9": "dance-tiktok9",
    "tiktok7": "idle-dance-tiktok7",
    "timejump": "emote-timejump",
    "tired": "emote-tired",
    "toilet": "idle-toilet",
    "touch": "dance-touch",
    "trampoline": "emote-trampoline",
    "tummy ache": "emoji-gagging",
    "uhmmm": "emote-thought",
    "uwu": "idle-uwu",
    "vogue hands": "dance-voguehands",
    "wait": "dance-wait",
    "walk-vertical": "walk-vertical",
    "wave": "emote-wave",  # Alias → wave
    "we have a strike!": "fishing-pull-small",
    "weird dance": "dance-weird",
    "wop dance": "dance-tiktok11",
    "wrong dance": "dance-wrong",
    "yes": "emote-yes",
    "yoga flow": "dance-spiritual",
    "zombie": "idle_zombie",
    "zombie run": "emote-zombierun",
}

# Nummer → Name (lowercase)
EMOTE_BY_NUM: dict[int, str] = {
    1: "advanced shy",
    2: "aerobics",
    3: "air guitar",
    4: "amused",
    5: "angry",
    6: "anime dance",
    7: "annoyed",
    8: "arrogance",
    9: "astronaut",
    10: "at attention",
    11: "attention",
    12: "attentive",
    13: "blast off",
    14: "blowing kisses",
    15: "boo",
    16: "boogie swing",
    17: "bow",
    18: "boxer",
    19: "breakdance",
    20: "bummed",
    21: "bunny hop",
    22: "casting!",
    23: "casual dance",
    24: "celebration step",
    25: "charging",
    26: "cheer",
    27: "chillin'",
    28: "clap",
    29: "clumsy",
    30: "cold",
    31: "collapse",
    32: "confusion",
    33: "cozy nap",
    34: "creepy puppet",
    35: "creepycute",
    36: "crouch",
    37: "cursing emote",
    38: "curtsy",
    39: "cute",
    40: "cute salute",
    41: "cutey",
    42: "dab",
    43: "dance zombie",
    44: "dance-anime3",
    45: "dance-kid",
    46: "dance-shuffle",
    47: "dance-tiktok1",
    48: "dance-tiktok15",
    49: "dance-tiktok16",
    50: "dance-tiktok3",
    51: "dance-tiktok4",
    52: "dance-tiktok5",
    53: "dance-tiktok6",
    54: "dance-tiktok7",
    55: "disco",
    56: "ditzy pose",
    57: "don't start now",
    58: "don't touch dance",
    59: "duck walk",
    60: "elbow bump",
    61: "embarrassed",
    62: "emoji-shush",
    63: "emote-armcannon",
    64: "emote-cartwheel",
    65: "emote-confused2",
    66: "emote-dinner",
    67: "emote-dramatic",
    68: "emote-electrified",
    69: "emote-fading",
    70: "emote-fail3",
    71: "emote-fireworks",
    72: "emote-flirt",
    73: "emote-gooey",
    74: "emote-handwalk",
    75: "emote-holding-hot-cocoa",
    76: "emote-hopscotch",
    77: "emote-juggling",
    78: "emote-kissing-passionate",
    79: "emote-mittens",
    80: "emote-oops",
    81: "emote-opera",
    82: "emote-outfit",
    83: "emote-outfit2",
    84: "emote-pose11",
    85: "emote-pose12",
    86: "emote-pose13",
    87: "emote-pose2",
    88: "emote-receive-disappointed",
    89: "emote-receive-happy",
    90: "emote-runhop",
    91: "emote-sheephop",
    92: "emote-shocked",
    93: "emote-surf",
    94: "emote-theatrical-test",
    95: "emote-thief",
    96: "emote-twitched",
    97: "emote-wavey",
    98: "energy ball",
    99: "enthused",
    100: "exasperated",
    101: "eyeroll",
    102: "face palm",
    103: "faint",
    104: "faint drop",
    105: "fairy float",
    106: "fairy twirl",
    107: "fall",
    108: "falling apart",
    109: "fashionista",
    110: "feel the beat",
    111: "fighter idle",
    112: "fireball lunge",
    113: "flex",
    114: "flirty wave",
    115: "float",
    116: "floss",
    117: "frog",
    118: "frolic ",
    119: "fruity dance",
    120: "frustrated",
    121: "gangnam style",
    122: "gasp",
    123: "ghost",
    124: "ghost float",
    125: "give up",
    126: "graceful",
    127: "gravity",
    128: "greedy emote",
    129: "hands in the air",
    130: "handstand",
    131: "happy",
    132: "harlem shake",
    133: "head blowup",
    134: "headball",
    135: "heart eyes",
    136: "heart fingers",
    137: "heart shape",
    138: "hello",
    139: "hero entrance",
    140: "hero pose",
    141: "hip hop dance",
    142: "hip shake",
    143: "home run!",
    144: "hug",
    145: "hug yourself",
    146: "hyped",
    147: "i believe i can fly",
    148: "ice cream dance",
    149: "ice skating",
    150: "idle-cold",
    151: "idle-dance-tiktok6",
    152: "idle-headless",
    153: "idle-phone",
    154: "idle-space",
    155: "idle_tough",
    156: "ignition boost",
    157: "imaginary jetpack",
    158: "irritated",
    159: "jinglebell",
    160: "judo chop",
    161: "jump",
    162: "k-pop dance",
    163: "karate",
    164: "karma dance",
    165: "kawaii",
    166: "kawaiigogo",
    167: "kiss",
    168: "laid back",
    169: "landing a fish!",
    170: "laugh",
    171: "laugh",
    172: "launch",
    173: "let's go shopping",
    174: "level up!",
    175: "levitate",
    176: "lying",
    177: "macarena",
    178: "magnetic",
    179: "maniac",
    180: "mind blown",
    181: "mining-fail",
    182: "mining-mine",
    183: "mining-success",
    184: "model",
    185: "monster fail",
    186: "moonlit howl",
    187: "moonwalk",
    188: "muscle pose",
    189: "naughty",
    190: "nervous",
    191: "night fever",
    192: "ninja run",
    193: "no",
    194: "nocturnal howl",
    195: "now we wait...",
    196: "orange juice dance",
    197: "panic",
    198: "party time!",
    199: "peace",
    200: "peekaboo!",
    201: "penguin dance",
    202: "penny's dance",
    203: "point",
    204: "poke dance",
    205: "ponder",
    206: "pose 1",
    207: "pose 10",
    208: "pose 3",
    209: "pose 5",
    210: "pose 7",
    211: "pose 8",
    212: "posh",
    213: "pouty face",
    214: "pray",
    215: "proposing",
    216: "punch",
    217: "punk guitar",
    218: "puppet",
    219: "push it",
    220: "push ups",
    221: "rainbow",
    222: "raise the roof",
    223: "relaxed",
    224: "relaxed",
    225: "relaxing",
    226: "repose",
    227: "rest",
    228: "revival",
    229: "ring on it",
    230: "robot",
    231: "robotic",
    232: "rock out",
    233: "rofl!",
    234: "roll",
    235: "rope pull",
    236: "run-vertical",
    237: "russian dance",
    238: "sad",
    239: "savage dance",
    240: "scritchy",
    241: "secret handshake",
    242: "sexy dance",
    243: "shrink",
    244: "shy",
    245: "shy",
    246: "sick",
    247: "singing",
    248: "sit",
    249: "sit-chair",
    250: "slap",
    251: "sleepy",
    252: "sleepy",
    253: "sleigh",
    254: "smirk",
    255: "smoothwalk",
    256: "snake",
    257: "sneeze",
    258: "snow angel",
    259: "snowball fight!",
    260: "sob",
    261: "splits drop",
    262: "star gazing",
    263: "stargazing",
    264: "stinky",
    265: "stunned",
    266: "sumo fight",
    267: "super kick",
    268: "super punch",
    269: "super run",
    270: "superpose",
    271: "surprisebig",
    272: "sweating",
    273: "sweet smooch",
    274: "swordfight",
    275: "tap dance",
    276: "tap loop",
    277: "telekinesis",
    278: "teleporting",
    279: "the wave",
    280: "theatrical",
    281: "think",
    282: "this is for you",
    283: "thumb suck",
    284: "thumbs up",
    285: "tiktok dance 10",
    286: "tiktok dance 4",
    287: "tiktok dance 9",
    288: "tiktok7",
    289: "timejump",
    290: "tired",
    291: "toilet",
    292: "touch",
    293: "trampoline",
    294: "tummy ache",
    295: "uhmmm",
    296: "uwu",
    297: "vogue hands",
    298: "wait",
    299: "walk-vertical",
    300: "we have a strike!",
    301: "weird dance",
    302: "wop dance",
    303: "wrong dance",
    304: "yes",
    305: "yoga flow",
    306: "zombie",
    307: "zombie run",
}

# Reverse Lookup: emote_id → name
EMOTE_ID_TO_NAME: dict[str, str] = {v: k for k, v in EMOTES.items()}
